engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.html"
exclude_paths:
  - "css/own.carousel.css"
  - "js/jquery.carousel.js"
  - "js/nivo-lightbox.min.js"
  - "js/owl.carousel.js"
 

